server:
  port: 8090
spring:
  application:
    name: nacos-demo
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.182.138:8848
        username: nacos
        password: nacos
        namespace: public