# 端口号
server:
  port: 8080
# 应用名称
spring:
  application:
    name: springboot
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/world?useUnicode=true&characterEncoding=utf8
    hikari:
      pool-name: hikariCP
      #最小空闲连接数
      minimum-idle: 5
      #空闲链接最大存活时间，默认为600000(10分钟)
      idle-timeout: 1800000
      #最大连接数
      maximum-pool-size: 10
      #从连接池返回的链接自动提交
      auto-commit: true
      #链接最大存活时间，0表示永久存活
      max-lifetime: 1800000
      #连接超时时间，默认30秒
      connection-timeout: 30000

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

